class Flag {
  Flag._();
  static const Map<String, String> allFlags = {
    'Qatar': 'assets/svg/flag/qa.svg',
    'Ecuador': 'assets/svg/flag/ec.svg',
    'Senegal': 'assets/svg/flag/sn.svg',
    'Netherlands': 'assets/svg/flag/nl.svg',
    'England': 'assets/svg/flag/en.svg',
    'Argentina': 'assets/svg/flag/ar.svg',
    'Denmark': 'assets/svg/flag/dk.svg',
    'Mexico': 'assets/svg/flag/mx.svg',
    'United States': 'assets/svg/flag/us.svg',
    'USA': 'assets/svg/flag/us.svg',
    'Morocco': 'assets/svg/flag/ma.svg',
    'Germany': 'assets/svg/flag/de.svg',
    'France': 'assets/svg/flag/fr.svg',
    'Spain': 'assets/svg/flag/es.svg',
    'Belgium': 'assets/svg/flag/be.svg',
    'Switzerland': 'assets/svg/flag/ch.svg',
    'Uruguay': 'assets/svg/flag/uy.svg',
    'Portugal': 'assets/svg/flag/pt.svg',
    'Brazil': 'assets/svg/flag/br.svg',
    'Wales': 'assets/svg/flag/ws.svg',
    'Poland': 'assets/svg/flag/pl.svg',
    'Tunisia': 'assets/svg/flag/tn.svg',
    'Croatia': 'assets/svg/flag/hr.svg',
    'Japan': 'assets/svg/flag/jp.svg',
    'Korea Republic': 'assets/svg/flag/kr.svg',
    'South Korea': 'assets/svg/flag/kr.svg',
    'Iran': 'assets/svg/flag/ir.svg',
    'Saudi Arabia': 'assets/svg/flag/sa.svg',
    'Canada': 'assets/svg/flag/ca.svg',
    'Ghana': 'assets/svg/flag/gh.svg',
    'Costa Rica': 'assets/svg/flag/cr.svg',
    'Serbia': 'assets/svg/flag/rs.svg',
    'Australia': 'assets/svg/flag/au.svg',
    'Cameroon': 'assets/svg/flag/cm.svg',
  };
}
