class Store {
  Store._();
  static const Map<String, String> allStores = {
    'Qatar': 'qatar',
    'Ecuador': 'ecuador',
    'Senegal': 'senegal',
    'Netherlands': 'netherlands',
    'England': 'england',
    'Argentina': 'argentina',
    'Denmark': 'denmark',
    'Mexico': 'mexico',
    'United States': 'usa',
    'USA': 'usa',
    'Morocco': 'morocco',
    'Germany': 'germany',
    'France': 'france',
    'Spain': 'spain',
    'Belgium': 'belgium',
    'Switzerland': 'switzerland',
    'Uruguay': 'uruguay',
    'Portugal': 'portugal',
    'Brazil': 'brazil',
    'Wales': 'wales',
    'Poland': 'poland',
    'Tunisia': 'tunisia',
    'Croatia': 'croatia',
    'Japan': 'japan',
    'Korea Republic': 'korea-republic',
    'South Korea': 'korea-republic',
    'Iran': 'iran',
    'Saudi Arabia': 'saudi-arabia',
    'Canada': 'canada',
    'Ghana': 'ghana',
    'Costa Rica': 'costa-rica',
    'Serbia': 'serbia',
    'Australia': 'australia',
    'Cameroon': 'cameroon',
  };
}
